### ISSUE TITLE
请问能不能加个缓存呢？

### ISSUE THREAD

**Issue by Copyes** [Xaber20110202/atcon#1]
就是第一次取了值后，把结果缓存起来，第二次取的时候直接再从缓存里面取值就好了。使用map形式缓存呢？

**Comment by Xaber20110202** [comment]
其实遍历是基于conditions数据结构的，迭代基本只会进行states的次数，效率非常高，并且调用者知道自己要获取的状态在什么位置，需要传递predicate用于提取。另外，相同参数的提取，调用者自身可以用变量保存。
